### ISSUE TITLE
Add support for AsyncConfig & AsyncData

### ISSUE THREAD

**Issue by maxwellhadley** [rfxcom/node-rfxcom#100]
Non-existent transmitter objects for these packet types are referenced in `lib/index.js`, causing warning messages to be generated. They need to be implemented, even if only by non-functional stubs

**Comment by maxwellhadley** [comment]
Dummy transmitter objects now added  by PR #101. However it will be difficult to go any further without access to the actual hardware

**Comment by TotallyInformation** [comment]
Hi Max, getting this on my live instance of Node-RED (only just got round to doing a trace):

```
(node:10638) Warning: Accessing non-existent property 'AsyncConfig' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:675:11)
    at Object.get (internal/modules/cjs/loader.js:689:5)
    at Object.<anonymous> (/home/home/nrmain2/data/node_modules/rfxcom/lib/index.js:337:43)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/home/nrmain2/data/node_modules/rfxcom/index.js:1:18)
(node:10638) Warning: Accessing non-existent property 'AsyncData' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:675:11)
    at Object.get (internal/modules/cjs/loader.js:689:5)
    at Object.<anonymous> (/home/home/nrmain2/data/node_modules/rfxcom/lib/index.js:342:41)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/home/nrmain2/data/node_modules/rfxcom/index.js:1:18)
```

If you wanted to knock up a test version of the Node-RED node with an updated library, I'd be happy to test.
